### ISSUE TITLE
Styling-Documentation in the Docs

### ISSUE THREAD

**Issue by FabianWilms** [urdeveloper/ud-stepper#4]
Hello!

You already support styling many of the components inside the stepper and steps. Currently users of this component have to look in the code of your elements to find out which CSS-mixins you support where. Adding these mixins to the documentation would immensely enhance the time needed for new developers to adopt your component.

Kind regards
Fabian

**Comment by urdeveloper** [comment]
#5

**Comment by FabianWilms** [comment]
Great! Thank you very much!
